version: "3.9"
services:
  joborchestrator:
    image: "job-orchestrator:latest"
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
  nexus:
    image: "sonatype/nexus3:latest"
    ports:
      - "8081:8081"
