version: "3.9"
services:
  nexus:
    container_name: nexus
    hostname: nexus
    image: "sonatype/nexus3:latest"
    ports:
      - '8081:8081'
    volumes:
      - "nexus-data:/nexus-data sonatype/nexus3"

  joborchestrator:
    container_name: joborchestrator
    hostname: joborchestrator
    build: "."
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html/"

volumes:
  nexus-data:
